<?xml version="1.0"?>
<package format="3">
  <name>hybrid_navigation</name>
  <version>1.0.0</version>
  <description>Nav2 config, launch files and test environments for the D* Lite planner + TD3 controller</description>
  <maintainer email="mohamedalyabdelghafar@gmail.com">Mohamed Aly</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>gazebo_dev</build_depend>

  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_dstar_lite_planner</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>td3_controller</exec_depend>
  <exec_depend>turtlebot3_gazebo</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
